### ISSUE TITLE
[BUG] Cant find gmod connection

### ISSUE THREAD

**Issue by Be1zebub** [Earu/GTerm#2]
#### **Describe the bug**
Probably it doesnt works with steamcmd installation
i have few gmod instances installed with steam & steamcmd

#### **To Reproduce**
1. Install new gmod instance with steamcmd
2. Launch gterm
3. Launch gmod
4. See nothing

#### **Screenshots**
![image](https://github.com/Earu/GTerm/assets/34854689/346a1f77-823b-49b8-8320-af1a80fe6f30)
![image](https://github.com/Earu/GTerm/assets/34854689/df1f41a3-7888-4657-bcfd-02f6d7d8266d)

#### **System**
 - Win 10 22H2 build 19045.2486
 
#### **Log & details**
im running `H:/Desktop/Programms/steamcmd/gmod_clean/hl2.exe`  
[gterm.log](https://github.com/user-attachments/files/16045188/gterm.log)

**Comment by Earu** [comment]
Hi, thank you for reporting that bug, could you tell me whether `gmsv_xconsole_win32.dll` or `gmsv_xconsole_win64.dll` is in your `garrysmod/lua/bin` folder?

If not you may want to add both of them manually, you can find them here: https://github.com/Earu/GTerm/tree/master/Modules

Also from what it seems to me your steam library is not located where your gmod installation is, which is not a case that's currently handled I think.

The code for finding the game path can be found here: https://github.com/Earu/GTerm/blob/master/GmodInterop.cs#L148L191

Could you look in your steam libraries for this file `/steamapps/libraryfolders.vdf`? Check whether any of them has the Garry's Mod app id which is `4000`. This would be what you're looking for:

![image](https://github.com/Earu/GTerm/assets/20880060/3545e572-b2bf-4324-8049-72c2b84c55fd)

**Comment by Be1zebub** [comment]
> Hi, thank you for reporting that bug, could you tell me whether `gmsv_xconsole_win32.dll` or `gmsv_xconsole_win64.dll` is in your `garrysmod/lua/bin` folder?
> 
> If not you may want to add both of them manually, you can find them here: https://github.com/Earu/GTerm/tree/master/Modules

no i dont, because:
![image](https://github.com/Earu/GTerm/assets/34854689/f173a0a3-a016-4d4c-9632-1539c78e30b3)


> The code for finding the game path can be found here: https://github.com/Earu/GTerm/blob/master/GmodInterop.cs#L148L191

why dont handle running process?

**Comment by Earu** [comment]
Can I assume you solved your issue by adding the modules manually then?

As for the running process, I prefer to detect path depending on steam library, but I might add a fallback or a check in case the path of the binary and the path of the steam installation is different

**Comment by Be1zebub** [comment]
> Can I assume you solved your issue by adding the modules manually then?

didnt help

**Comment by Earu** [comment]
Oh whoops I forgot, you also need to modify the contents of `garrysmod/lua/menu/menu.lua`

Add the following after everything:
```lua
require("xconsole")
```

**Comment by Be1zebub** [comment]
ill test it in menu realm later, but it works on clientside 🎉 
![image](https://github.com/Earu/GTerm/assets/34854689/6ffdf76d-7ad5-4897-9890-8662cde4f1a5)

**Comment by Earu** [comment]
https://github.com/Earu/GTerm/commit/90f4f68e181c4c6142056322f55c53e72b4ee8fa

This should be fixed now, however you will need to restart Garry's Mod in some cases but GTerm should tell you when that's the case.
